### ISSUE TITLE
JDBC Virtual Layers example raises error

### ISSUE THREAD

**Issue by duckontheweb** [boundlessgeo/gsconfig#161]
I am following the example for creating a new JDBC Virtual Layer in the [documentation](https://github.com/boundlessgeo/gsconfig#more-examples---updated-for-geoserver-24). [This gist](https://gist.github.com/duckontheweb/431d41d8145335c58fded5dfb88fd18a) shows my adaptation of the demo for the table I am attempting to create (with the sensitive information changed).

Running this script returns the following error in the console:

```
Traceback (most recent call last):
  File "example-view.py", line 14, in <module>
    ft = cat.publish_featuretype(ft_name, store, epsg_code, jdbc_virtual_table=jdbc_vt)
  File "/Users/jduckwor/anaconda/envs/oc/lib/python2.7/site-packages/geoserver/catalog.py", line 663, in publish_featuretype
    feature_type.fetch()
  File "/Users/jduckwor/anaconda/envs/oc/lib/python2.7/site-packages/geoserver/support.py", line 176, in fetch
    self.dom = self.catalog.get_xml(self.href)
  File "/Users/jduckwor/anaconda/envs/oc/lib/python2.7/site-packages/geoserver/catalog.py", line 216, in get_xml
    raise FailedRequestError("Tried to make a GET request to %s but got a %d status code: \n%s" % (rest_url, response.status, content))
geoserver.catalog.FailedRequestError: Tried to make a GET request to http://maps-dev-map.nrel.gov/geoserver/rest/workspaces/nrel/datastores/area/featuretypes/area_caff_amap_arctic_3572.xml but got a 404 status code: 
No such feature type: nrel,area,area_caff_amap_arctic_3572
```

I have confirmed that the workspace and store both exist on the server. Is there an additional step I need to take to create a new virtual table?

Thanks very much for the help.

**Comment by duckontheweb** [comment]
UPDATE: After looking into this some more, it looks like the problem was that the feature was not being posted successfully and therefore did not exist to be fetched. I was getting a `301` status code on the response when I logged the response from [this line](https://github.com/boundlessgeo/gsconfig/blob/master/src/geoserver/catalog.py#L662) in my local copy. It might be worth checking for a successful response in the headers before running the fetch in the following line.
