### ISSUE TITLE
Unable to add ImageMosaics

### ISSUE THREAD

**Issue by iatkin** [boundlessgeo/gsconfig#188]
Hi. I'm trying to use gsconfig to add an image mosaic backed by Postgres (rather than a shape file) and am unable to do so. I get this error:

```
Traceback (most recent call last):
  File "/tmp/add_files.py", line 15, in <module>
    catalog.create_imagemosaic(mosaic, zip_path, workspace=w) 
  File "/usr/lib/python2.7/site-packages/geoserver/catalog.py", line 499, in create_imagemosaic
    raise UploadError(response)
geoserver.catalog.UploadError: Could not aquire reader for coverage.
```

mosaic is a string for the store name and zip_path is also a string. An unusable datastore does get created (layers can't be derived from it), and the database table does not get created. The same *.properties in the zip file work without issue in the web interface. I don't have any problems with either external coverage stores or coverage stores using uploaded files.

**Comment by iatkin** [comment]
Seems to work without issue if just the directory is given
