### ISSUE TITLE
error in tomcat2.13.2

### ISSUE THREAD

**Issue by z954134** [boundlessgeo/gsconfig#190]
Traceback (most recent call last):
  File "D:/mystudy/python3/geoserverautoadd.py", line 42, in <module>
    hj=geocat.get_workspace("hj")
  File "C:\ProgramData\Anaconda3\lib\site-packages\geoserver\catalog.py", line 945, in get_workspace
    candidates = [w for w in self.get_workspaces() if w.name == name]
  File "C:\ProgramData\Anaconda3\lib\site-packages\geoserver\catalog.py", line 940, in get_workspaces
    description = self.get_xml(rest_url)
  File "C:\ProgramData\Anaconda3\lib\site-packages\geoserver\catalog.py", line 158, in get_xml
    text
geoserver.catalog.FailedRequestError: Tried to make a GET request to http://localhost:90/geoserver/workspaces.xml but got a 404 status code:

**Comment by z954134** [comment]
sorry ,I have error in gsconfig-py3
