### ISSUE TITLE
publish_featuretype fails when creating new PostGIS layer

### ISSUE THREAD

**Issue by chau-intl** [boundlessgeo/gsconfig#99]
When trying to create a new layer in GeoServer pointing at a PostGIS store I get the following result:

    geoserver.catalog.FailedRequestError: Tried to make a GET request to http://myserver:8080/geoserver/rest/workspaces/myworkspace/datastores/mystore/featuretypes/myview.xml but got a 404 status code: 
    b'No such feature type: myworkspace,mystore,myview'

I can publish the layer manually through the GeoServer admin web site.

My code is the following:

    catalog = Catalog('http://myserver:8080/geoserver/rest')
    workspace = catalog.get_workspace('myworkspace')
    data_store = catalog.get_store(‘mystore', workspace)    
    ft = catalog.publish_featuretype('myview', data_store, 'EPSG:4326', srs='EPSG:4326’)

Version information:

    GeoServer: 2.6.2 (the same in 2.5.2)
    gsConfig: 0.6.11
    PostGIS: 2.0.1

Geoserver log entries for the last line of code:

> 2015-05-12 14:02:20,656 DEBUG [geoserver.security] - AuthenticationCache found an entry for basic, admin:4c6133cfd067b2a5d15371b0db33fb81
> 2015-05-12 14:02:20,657 DEBUG [security.RESTfulPathBasedFilterInvocationDefinitionMap] - Converted URL to lowercase, from: '/rest/workspaces/myworkspace/datastores/mystore/featuretypes/myview.xml'; to: '/rest/workspaces/myworkspace/datastores/mystore/featuretypes/myview.xml'  and httpMethod= GET
> 2015-05-12 14:02:20,657 DEBUG [security.RESTfulPathBasedFilterInvocationDefinitionMap] - ~~~~~~~~~~ antPath= /** methodList= [GET]
> 2015-05-12 14:02:20,657 DEBUG [security.RESTfulPathBasedFilterInvocationDefinitionMap] - Candidate is: '/rest/workspaces/myworkspace/datastores/mystore/featuretypes/myview.xml'; antPath is /**; matchedPath=true; matchedMethods=true
> 2015-05-12 14:02:20,657 DEBUG [security.RESTfulPathBasedFilterInvocationDefinitionMap] - returning ADMIN
> 2015-05-12 14:02:20,657 TRACE [ows.OWSHandlerMapping] - No handler mapping found for [/rest/workspaces/myworkspace/datastores/mystore/featuretypes/myview.xml]
> 2015-05-12 14:02:20,657 TRACE [ows.OWSHandlerMapping] - No handler mapping found for [/rest/workspaces/myworkspace/datastores/mystore/featuretypes/myview.xml]
> 2015-05-12 14:02:20,657 TRACE [ows.OWSHandlerMapping] - No handler mapping found for [/rest/workspaces/myworkspace/datastores/mystore/featuretypes/myview.xml]
> 2015-05-12 14:02:20,659 DEBUG [org.geoserver] - Thread 40 locking in mode READ
> 2015-05-12 14:02:20,663 DEBUG [org.geoserver] - Thread 40 got the lock in mode READ
> 2015-05-12 14:02:20,757 DEBUG [org.geoserver] - Thread 40 releasing the lock in mode READ
> 2015-05-12 14:02:20,757 ERROR [geoserver.rest] - No such feature type: myworkspace,mystore,myview
> 2015-05-12 14:02:20,758 DEBUG [geoserver.filters] - Compressing output for mimetype: text/plain
> 2015-05-12 14:02:20,758 ERROR [geoserver.rest] - 
> org.geoserver.rest.RestletException
> 	at org.geoserver.catalog.rest.FeatureTypeFinder.findTarget(FeatureTypeFinder.java:48)
> 	at org.restlet.Finder.handle(Finder.java:268)
> 	at org.geoserver.rest.BeanDelegatingRestlet.handle(BeanDelegatingRestlet.java:38)
> 	at org.restlet.Filter.doHandle(Filter.java:105)
> 	at org.restlet.Filter.handle(Filter.java:134)
> 	at org.restlet.Router.handle(Router.java:444)
> 	at org.geoserver.rest.RESTDispatcher$1.handle(RESTDispatcher.java:205)
> 	at com.noelios.restlet.ext.servlet.ServletConverter.service(ServletConverter.java:129)
> 	at org.geoserver.rest.RESTDispatcher.handleRequestInternal(RESTDispatcher.java:87)
> 	at org.springframework.web.servlet.mvc.AbstractController.handleRequest(AbstractController.java:153)
> 	at org.springframework.web.servlet.mvc.SimpleControllerHandlerAdapter.handle(SimpleControllerHandlerAdapter.java:48)
> 	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:923)
> 	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:852)
> 	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:882)
> 	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:778)
> 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:620)
> 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:727)
> 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
> 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
> 	at org.geoserver.filters.ThreadLocalsCleanupFilter.doFilter(ThreadLocalsCleanupFilter.java:28)
> 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
> 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
> 	at org.geoserver.filters.SpringDelegatingFilter$Chain.doFilter(SpringDelegatingFilter.java:75)
> 	at org.geoserver.wms.animate.AnimatorFilter.doFilter(AnimatorFilter.java:71)
> 	at org.geoserver.filters.SpringDelegatingFilter$Chain.doFilter(SpringDelegatingFilter.java:71)
> 	at org.geoserver.filters.SpringDelegatingFilter.doFilter(SpringDelegatingFilter.java:46)
> 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
> 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
> 	at org.geoserver.platform.AdvancedDispatchFilter.doFilter(AdvancedDispatchFilter.java:50)
> 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
> 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
> 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:311)
> 	at org.geoserver.security.filter.GeoServerCompositeFilter$NestedFilterChain.doFilter(GeoServerCompositeFilter.java:69)
> 	at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.invoke(FilterSecurityInterceptor.java:116)
> 	at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.doFilter(FilterSecurityInterceptor.java:83)
> 	at org.geoserver.security.filter.GeoServerCompositeFilter$NestedFilterChain.doFilter(GeoServerCompositeFilter.java:73)
> 	at org.geoserver.security.filter.GeoServerCompositeFilter.doFilter(GeoServerCompositeFilter.java:92)
> 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:323)
> 	at org.geoserver.security.filter.GeoServerCompositeFilter$NestedFilterChain.doFilter(GeoServerCompositeFilter.java:69)
> 	at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:113)
> 	at org.geoserver.security.filter.GeoServerCompositeFilter$NestedFilterChain.doFilter(GeoServerCompositeFilter.java:73)
> 	at org.geoserver.security.filter.GeoServerCompositeFilter.doFilter(GeoServerCompositeFilter.java:92)
> 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:323)
> 	at org.geoserver.security.filter.GeoServerAnonymousAuthenticationFilter.doFilter(GeoServerAnonymousAuthenticationFilter.java:54)
> 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:323)
> 	at org.geoserver.security.filter.GeoServerCompositeFilter$NestedFilterChain.doFilter(GeoServerCompositeFilter.java:69)
> 	at org.springframework.security.web.authentication.www.BasicAuthenticationFilter.doFilter(BasicAuthenticationFilter.java:201)
> 	at org.geoserver.security.filter.GeoServerCompositeFilter$NestedFilterChain.doFilter(GeoServerCompositeFilter.java:73)
> 	at org.geoserver.security.filter.GeoServerCompositeFilter.doFilter(GeoServerCompositeFilter.java:92)
> 	at org.geoserver.security.filter.GeoServerBasicAuthenticationFilter.doFilter(GeoServerBasicAuthenticationFilter.java:83)
> 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:323)
> 	at org.geoserver.security.filter.GeoServerCompositeFilter$NestedFilterChain.doFilter(GeoServerCompositeFilter.java:69)
> 	at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:87)
> 	at org.geoserver.security.filter.GeoServerSecurityContextPersistenceFilter$1.doFilter(GeoServerSecurityContextPersistenceFilter.java:53)
> 	at org.geoserver.security.filter.GeoServerCompositeFilter$NestedFilterChain.doFilter(GeoServerCompositeFilter.java:73)
> 	at org.geoserver.security.filter.GeoServerCompositeFilter.doFilter(GeoServerCompositeFilter.java:92)
> 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:323)
> 	at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:173)
> 	at org.geoserver.security.GeoServerSecurityFilterChainProxy.doFilter(GeoServerSecurityFilterChainProxy.java:135)
> 	at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:346)
> 	at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:259)
> 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
> 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
> 	at org.geoserver.filters.LoggingFilter.doFilter(LoggingFilter.java:76)
> 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
> 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
> 	at org.geoserver.filters.GZIPFilter.doFilter(GZIPFilter.java:42)
> 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
> 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
> 	at org.geoserver.filters.SessionDebugFilter.doFilter(SessionDebugFilter.java:48)
> 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
> 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
> 	at org.geoserver.filters.FlushSafeFilter.doFilter(FlushSafeFilter.java:44)
> 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
> 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
> 	at org.vfny.geoserver.filters.SetCharacterEncodingFilter.doFilter(SetCharacterEncodingFilter.java:109)
> 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
> 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
> 	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:220)
> 	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122)
> 	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:501)
> 	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:171)
> 	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
> 	at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:950)
> 	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
> 	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:408)
> 	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1070)
> 	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:611)
> 	at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:316)
> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
> 	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
> 	at java.lang.Thread.run(Thread.java:745)

**Comment by meilinger** [comment]
Running into the same issue.

**Comment by giserd** [comment]
It because the geoserver didn't have the store or layer, you should check the geoserver store

**Comment by giserd** [comment]
1.you should have a store(connect the Postgis) named 'StoreName' , a layer named 'LayerName' and a workspace named 'Workspace'
2.
cat = Catalog('http://www.***********.com:8080/geoserver/rest','****','******')
workspace = cat.get_workspace('WorkSpace')
data_store = cat.get_store('StoreName', workspace) 
Published = cat.publish_featuretype('LayerName',data_store,'3857')
3.end

**Comment by riaanvddool** [comment]
Same issue.

ds = cat.create_datastore('postgisdb', workspace)
ds.connection_parameters.update(host='postgis', port='5432', database='gis', user='docker', passwd='docker', dbtype='postgis', schema='public')
cat.save(ds)

ft = cat.publish_featuretype('my_postgis_table', ds, 'EPSG:4326', srs='EPSG:4326')

Causes:

<pre>
Traceback (most recent call last):
  File "./configure.py", line 43, in <module>
    ft = cat.publish_featuretype('my_postgis_table', ds, 'EPSG:4326', srs='EPSG:4326')
  File "/usr/local/lib/python2.7/dist-packages/geoserver/catalog.py", line 664, in publish_featuretype
    feature_type.fetch()
  File "/usr/local/lib/python2.7/dist-packages/geoserver/support.py", line 174, in fetch
    self.dom = self.catalog.get_xml(self.href)
  File "/usr/local/lib/python2.7/dist-packages/geoserver/catalog.py", line 216, in get_xml
    raise FailedRequestError("Tried to make a GET request to %s but got a %d status code: \n%s" % (rest_url, response.status, content))
geoserver.catalog.FailedRequestError: Tried to make a GET request to http://my.server.com/geoserver/rest/workspaces/ws/datastores/postgisdb/featuretypes/my_postgis_table.xml but got a 404 status code: 
No such feature type: ws,postgisdb,my_postgis_table
</pre>

I am not sure why publish_featuretype would do a GET request to the url where the feature needs to be published to. It doesnt make sense to me.

**Comment by riaanvddool** [comment]
OK, I found my problem. 

I missed an error message in the log that read: 
<pre>
Resource named 'my_postgis_table' already exists in namespace 'ws'
</pre>

I was using the same DB twice in the workspace while testing. So putting it in a separate workspace solved the issue.

**Comment by riaanvddool** [comment]
I am seeing this again but for a different reason: publishing a JDBCVirtualTable where the sql query returns no rows. After some debugging it seems that Geoserver is unable to calculate the bounding box for the layer. @chau-intl can you confirm if your table or view "myview" contains any rows?

https://github.com/boundlessgeo/gsconfig/blob/355219660ad3ce215609152f8e83a3ae9857b5a4/src/geoserver/catalog.py#L648

A solution would be to allow the bbox to be specified when the feature is published.

<pre>
nativeCRS: "GEOGCS["WGS 84", DATUM["World Geodetic System 1984", SPHEROID["WGS 84", 6378137.0, 298.257223563, AUTHORITY["EPSG","7030"]], AUTHORITY["EPSG","6326"]], PRIMEM["Greenwich", 0.0, AUTHORITY["EPSG","8901"]], UNIT["degree", 0.017453292519943295], AXIS["Geodetic longitude", EAST], AXIS["Geodetic latitude", NORTH], AUTHORITY["EPSG","4326"]]",
srs: "EPSG:4326",
nativeBoundingBox: {
minx: 10,
maxx: 66,
miny: -50,
maxy: 10,
crs: "EPSG:4326"
},
latLonBoundingBox: {
minx: 10,
maxx: 66,
miny: -50,
maxy: 10,
crs: "GEOGCS["WGS84(DD)", DATUM["WGS84", SPHEROID["WGS84", 6378137.0, 298.257223563]], PRIMEM["Greenwich", 0.0], UNIT["degree", 0.017453292519943295], AXIS["Geodetic longitude", EAST], AXIS["Geodetic latitude", NORTH]]"
},

</pre>

**Comment by MrZogs** [comment]
Same issue here too.
```
DS = cat.create_datastore('DS','WS')

  Published = cat.publish_featuretype('LayerName',DS,'3857') 
  File "/home/user/AutoService/gsconfig/src/geoserver/catalog.py", line 664, in publish_featuretype
    feature_type.fetch()
  File "/home/user/AutoService/gsconfig/src/geoserver/support.py", line 174, in fetch
    self.dom = self.catalog.get_xml(self.href)
  File "/home/user/AutoService/gsconfig/src/geoserver/catalog.py", line 216, in get_xml
    raise FailedRequestError("Tried to make a GET request to %s but got a %d status code: \n%s" % (rest_url, response.status, content))
geoserver.catalog.FailedRequestError: Tried to make a GET request to http://localhost:8080/geoserver/rest/workspaces/WS/datastores/DS/featuretypes/LayerName.xml but got a 404 status code: 
No such feature type: WS, DS,LayerName
```
> I am not sure why publish_featuretype would do a GET request to the url where the feature needs to be published to. It doesnt make sense to me.

In fact, it will perform a GET to return the final feature type after being made. To make a featuretype it will perform a POST before that as you may see on [geoserver.catalog.py](https://github.com/boundlessgeo/gsconfig/blob/355219660ad3ce215609152f8e83a3ae9857b5a4/src/geoserver/catalog.py#L663). This may help to find what error may be you could occur by print out the response from the HTTPrequest by writing after httprequest `print response`

In my case, it seems that i am `Trying to create new feature type inside the store, but no attributes were specified`. Can anyone guess what attribute am i missing?

**Comment by ReadMost** [comment]
Hello everyone, I have a problem with 'ws = cat.get_workspace('some_sapce')'. It works locally on my laptop, however does not on server. Problem is [https://stackoverflow.com/questions/52238976/python-django-code-works-locally-but-on-server-raise-failed-to-establish-a-new](url) and below, Thanks for any help

> ConnectionError at /backends/profile/ HTTPSConnectionPool(host='geo.egistic.kz', port=8081): Max retries exceeded with url: /rest/workspaces.xml (Caused by NewConnectionError(': Failed to establish a new connection: [Errno 110] Connection timed out',))
